use std::{
    ffi::{CStr, CString},
    fs::File,
    io::{self, Read},
    process,
    sync::{Arc, Mutex},
};

use libc::{EEXIST, EINVAL, c_long, c_void, syscall, uid_t};
use log::{error, info, warn};

use crate::package::{read_ap_package_config, synchronize_package_uid};

// Generated by build.rs from app/src/main/cpp/version (single source of the
// KernelPatch version embedded into supercalls).
include!(concat!(env!("OUT_DIR"), "/kp_version.rs"));

const KSTORAGE_EXCLUDE_LIST_GROUP: i32 = 1;
const KSTORAGE_AUTO_EXCLUDE_GROUP: i32 = 3;

const __NR_SUPERCALL: c_long = 45;
const SUPERCALL_SU: c_long = 0x1010;
const SUPERCALL_KSTORAGE_WRITE: c_long = 0x1041;
const SUPERCALL_KSTORAGE_READ: c_long = 0x1042;
const SUPERCALL_CONTROL_FEATURE: c_long = 0x1046;
const SUPERCALL_SU_GRANT_UID: c_long = 0x1100;
const SUPERCALL_SU_REVOKE_UID: c_long = 0x1101;
const SUPERCALL_SU_NUMS: c_long = 0x1102;
const SUPERCALL_SU_LIST: c_long = 0x1103;
const SUPERCALL_SU_RESET_PATH: c_long = 0x1111;
const SUPERCALL_SU_GET_SAFEMODE: c_long = 0x1112;

const SUPERCALL_KPM_LOAD: c_long = 0x1020;

const SUPERCALL_UTS_SET: c_long = 0x1050;
const SUPERCALL_UTS_RESET: c_long = 0x1051;
const SUPERCALL_REPORT_EVENT: c_long = 0x1080;

const SUPERCALL_PATHHIDE_ENABLE: c_long = 0x1064;
const SUPERCALL_PATHHIDE_ADD: c_long = 0x1060;
const SUPERCALL_PATHHIDE_CLEAR: c_long = 0x1063;
const SUPERCALL_PATHHIDE_UID_MODE: c_long = 0x106A;
const SUPERCALL_PATHHIDE_UID_ADD: c_long = 0x1066;
const SUPERCALL_PATHHIDE_UID_CLEAR: c_long = 0x1069;
const SUPERCALL_PATHHIDE_FILTER_SYSTEM: c_long = 0x106B;

const SUPERCALL_NETISOLATE_ENABLE: c_long = 0x1070;
const SUPERCALL_NETISOLATE_UID_ADD: c_long = 0x1072;
const SUPERCALL_NETISOLATE_UID_REMOVE: c_long = 0x1073;
const SUPERCALL_NETISOLATE_UID_LIST: c_long = 0x1074;
const SUPERCALL_NETISOLATE_UID_CLEAR: c_long = 0x1075;

const SUPERCALL_SCONTEXT_LEN: usize = 0x60;

#[repr(C)]
struct SuProfile {
    uid: i32,
    to_uid: i32,
    scontext: [u8; SUPERCALL_SCONTEXT_LEN],
}

fn ver_and_cmd(cmd: c_long) -> c_long {
    let version_code: u32 = ((KP_MAJOR << 16) + (KP_MINOR << 8) + KP_PATCH)
        .try_into()
        .unwrap();
    ((version_code as c_long) << 32) | (0x1158 << 16) | (cmd & 0xFFFF)
}

pub fn report_kernel_event(superkey: &Option<String>, event: &str, state: &str) -> c_long {
    let Some(key) = convert_superkey(superkey) else {
        return (-EINVAL).into();
    };
    let Ok(event) = CString::new(event) else {
        return (-EINVAL).into();
    };
    let Ok(state) = CString::new(state) else {
        return (-EINVAL).into();
    };
    unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_REPORT_EVENT),
            event.as_ptr(),
            state.as_ptr(),
        ) as c_long
    }
}

fn sc_su_revoke_uid(key: &CStr, uid: uid_t) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_SU_REVOKE_UID),
            uid,
        ) as c_long
    }
}

fn sc_su_grant_uid(key: &CStr, profile: &SuProfile) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_SU_GRANT_UID),
            profile,
        ) as c_long
    }
}

fn sc_kstorage_write(
    key: &CStr,
    gid: i32,
    did: i64,
    data: *mut c_void,
    offset: i32,
    dlen: i32,
) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_KSTORAGE_WRITE),
            gid as c_long,
            did as c_long,
            data,
            (((offset as i64) << 32) | (dlen as i64)) as c_long,
        ) as c_long
    }
}

fn sc_kstorage_read(
    key: &CStr,
    gid: i32,
    did: i64,
    out_data: *mut c_void,
    offset: i32,
    dlen: i32,
) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_KSTORAGE_READ),
            gid as c_long,
            did as c_long,
            out_data,
            (((offset as i64) << 32) | (dlen as i64)) as c_long,
        ) as c_long
    }
}

fn sc_set_ap_mod_exclude(key: &CStr, uid: i64, exclude: i32) -> c_long {
    sc_kstorage_write(
        key,
        KSTORAGE_EXCLUDE_LIST_GROUP,
        uid,
        &exclude as *const i32 as *mut c_void,
        0,
        size_of::<i32>() as i32,
    )
}

pub fn get_new_app_profile_mode() -> i32 {
    let key = CStr::from_bytes_with_nul(b"su\0").expect("auto exclude key init failed");
    let mut enabled = 0_i32;
    let rc = sc_kstorage_read(
        key,
        KSTORAGE_AUTO_EXCLUDE_GROUP,
        0,
        &mut enabled as *mut i32 as *mut c_void,
        0,
        size_of::<i32>() as i32,
    );
    if rc < 0 {
        return 0;
    }
    enabled
}

pub fn sc_su_get_safemode(key: &CStr) -> c_long {
    if key.to_bytes().is_empty() {
        warn!("[sc_su_get_safemode] null superkey, tell apd we are not in safemode!");
        return 0;
    }

    let key_ptr = key.as_ptr();
    if key_ptr.is_null() {
        warn!("[sc_su_get_safemode] superkey pointer is null!");
        return 0;
    }

    unsafe {
        syscall(
            __NR_SUPERCALL,
            key_ptr,
            ver_and_cmd(SUPERCALL_SU_GET_SAFEMODE),
        ) as c_long
    }
}

fn sc_su(key: &CStr, profile: &SuProfile) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    let rc = unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_SU),
            profile,
        ) as c_long
    };
    info!("[diag:sc_su] key_len={} rc={}", key.to_bytes().len(), rc);
    rc
}

fn sc_su_reset_path(key: &CStr, path: &CStr) -> c_long {
    if key.to_bytes().is_empty() || path.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_SU_RESET_PATH),
            path.as_ptr(),
        ) as c_long
    }
}

fn sc_control_feature(key: &CStr, name: &CStr, enable: bool) -> c_long {
    if key.to_bytes().is_empty() || name.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_CONTROL_FEATURE),
            name.as_ptr(),
            if enable { 1i64 } else { 0i64 },
        ) as c_long
    }
}

pub fn apply_sucompat(superkey: &Option<String>) {
    if !std::path::Path::new(crate::defs::SUCOMPAT_FILE).exists() {
        info!("[sucompat] disabled, skipping");
        return;
    }

    let Some(key) = convert_superkey(superkey) else {
        warn!("[sucompat] no superkey available");
        return;
    };
    let name = CStr::from_bytes_with_nul(b"sucompat_extra\0")
        .expect("sucompat feature name must be valid");
    let rc = sc_control_feature(&key, name, true);
    if rc < 0 {
        warn!("[sucompat] restore failed: {}", rc);
    } else {
        info!("[sucompat] restored from persistent config");
    }
}

fn sc_kpm_load(key: &CStr, path: &CStr, args: &CStr) -> c_long {
    if key.to_bytes().is_empty() || path.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    let rc = unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_KPM_LOAD),
            path.as_ptr(),
            args.as_ptr(),
            std::ptr::null::<c_void>(),
        ) as c_long
    };
    info!(
        "[diag:sc_kpm_load] key_len={} path={} rc={}",
        key.to_bytes().len(),
        path.to_string_lossy(),
        rc
    );
    rc
}

fn sc_su_uid_nums(key: &CStr) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    unsafe { syscall(__NR_SUPERCALL, key.as_ptr(), ver_and_cmd(SUPERCALL_SU_NUMS)) as c_long }
}

fn sc_su_allow_uids(key: &CStr, buf: &mut [uid_t]) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    if buf.is_empty() {
        return (-EINVAL).into();
    }
    unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_SU_LIST),
            buf.as_mut_ptr(),
            buf.len() as i32,
        ) as c_long
    }
}

fn read_file_to_string(path: &str) -> io::Result<String> {
    let mut file = File::open(path)?;
    let mut content = String::new();
    file.read_to_string(&mut content)?;
    Ok(content)
}

fn convert_string_to_u8_array(s: &str) -> [u8; SUPERCALL_SCONTEXT_LEN] {
    let mut u8_array = [0u8; SUPERCALL_SCONTEXT_LEN];
    let bytes = s.as_bytes();
    let len = usize::min(SUPERCALL_SCONTEXT_LEN, bytes.len());
    u8_array[..len].copy_from_slice(&bytes[..len]);
    u8_array
}

fn convert_superkey(s: &Option<String>) -> Option<CString> {
    let result = s.as_ref().and_then(|s| CString::new(s.clone()).ok());
    if let Some(ref cs) = result {
        info!("[diag:convert_superkey] input_present=true cstr_len={}", cs.to_bytes().len());
    } else {
        warn!("[diag:convert_superkey] input_present={} result=None", s.is_some());
    }
    result
}

fn set_retry_flag(path: &str, enabled: bool, label: &str) {
    let result = if enabled {
        std::fs::write(path, b"1")
    } else {
        match std::fs::remove_file(path) {
            Ok(()) => Ok(()),
            Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(()),
            Err(e) => Err(e),
        }
    };

    if let Err(e) = result {
        let action = if enabled { "write" } else { "clear" };
        warn!(
            "[{}] failed to {} retry flag '{}': {}",
            label, action, path, e
        );
    }
}

pub fn refresh_ap_package_list(skey: &CStr, mutex: &Arc<Mutex<()>>) {
    let _lock = mutex.lock().unwrap();

    if let Err(e) = synchronize_package_uid() {
        error!("Failed to synchronize package UIDs: {}", e);
    }

    let package_configs = read_ap_package_config();

    // The manager is the recovery path for APD. Never leave its UID in the
    // kernel exclude list, even if an older auto-profile pass added it.
    if let Ok(manager_pkg) = std::fs::read_to_string(crate::defs::MANAGER_PACKAGE_FILE) {
        let manager_pkg = manager_pkg.trim();
        if !manager_pkg.is_empty() {
            if let Ok(packages) = std::fs::read_to_string("/data/system/packages.list") {
                if let Some(uid) = packages.lines().find_map(|line| {
                    let mut fields = line.split_whitespace();
                    (fields.next() == Some(manager_pkg))
                        .then(|| fields.next()?.parse::<i64>().ok())
                        .flatten()
                }) {
                    let rc = sc_set_ap_mod_exclude(skey, uid, 0);
                    info!("[refresh_su_list] Clearing manager exclude {} ({}) result={}", manager_pkg, uid, rc);
                }
            }
        }
    }

    let num = sc_su_uid_nums(skey);
    if num < 0 {
        error!("[refresh_su_list] Error getting number of UIDs: {}", num);
        return;
    }
    let num = num as usize;
    let mut uids = vec![0 as uid_t; num];
    let n = sc_su_allow_uids(skey, &mut uids);
    if n < 0 {
        error!("[refresh_su_list] Error getting su list");
        return;
    }

    let granted_uids: std::collections::HashSet<uid_t> = package_configs
        .iter()
        .filter(|c| c.allow == 1 && c.exclude == 0)
        .map(|c| c.uid as uid_t)
        .collect();

    for uid in &uids {
        if *uid == 0 || *uid == 2000 {
            continue;
        }
        if granted_uids.contains(uid) {
            continue;
        }
        info!(
            "[refresh_ap_package_list] Revoking {} root permission...",
            uid
        );
        let rc = sc_su_revoke_uid(skey, *uid);
        if rc != 0 {
            error!("[refresh_ap_package_list] Error revoking UID: {}", rc);
        }
    }

    for config in &package_configs {
        if config.allow == 1 && config.exclude == 0 {
            let profile = SuProfile {
                uid: config.uid,
                to_uid: config.to_uid,
                scontext: convert_string_to_u8_array(&config.sctx),
            };
            let result = sc_su_grant_uid(skey, &profile);
            info!(
                "[refresh_ap_package_list] Loading {}: result = {}",
                config.pkg, result
            );
        }
        if config.allow == 0 && config.exclude == 1 {
            let result = sc_set_ap_mod_exclude(skey, config.uid as i64, 1);
            info!(
                "[refresh_ap_package_list] Loading exclude {}: result = {}",
                config.pkg, result
            );
        }
    }
}

pub fn privilege_apd_profile(superkey: &Option<String>) {
    let key = convert_superkey(superkey);

    let all_allow_ctx = "u:r:magisk:s0";
    let profile = SuProfile {
        uid: process::id().try_into().expect("PID conversion failed"),
        to_uid: 0,
        scontext: convert_string_to_u8_array(all_allow_ctx),
    };
    if let Some(ref key) = key {
        info!("[diag:privilege] key_len={} key_is_empty={}", key.to_bytes().len(), key.to_bytes().is_empty());
        let result = sc_su(key, &profile);
        info!("[privilege_apd_profile] result = {}", result);
    } else {
        warn!("[diag:privilege] superkey is None!");
    }
}

pub fn init_load_su_path(superkey: &Option<String>) {
    let su_path_file = "/data/adb/ap/su_path";

    match read_file_to_string(su_path_file) {
        Ok(su_path) => {
            let superkey_cstr = convert_superkey(superkey);

            match superkey_cstr {
                Some(superkey_cstr) => match CString::new(su_path.trim()) {
                    Ok(su_path_cstr) => {
                        let result = sc_su_reset_path(&superkey_cstr, &su_path_cstr);
                        if result == 0 {
                            info!("suPath load successfully");
                        } else {
                            warn!("Failed to load su path, error code: {}", result);
                        }
                    }
                    Err(e) => {
                        warn!("Failed to convert su_path: {}", e);
                    }
                },
                _ => {
                    warn!("Superkey is None, skipping...");
                }
            }
        }
        Err(e) => {
            warn!("Failed to read su_path file: {}", e);
        }
    }
}

fn sc_pathhide_enable(key: &CStr, enable: bool) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    let rc = unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_PATHHIDE_ENABLE),
            if enable { 1i64 } else { 0i64 },
        ) as c_long
    };
    info!("[diag:sc_pathhide_enable] key_len={} enable={} rc={}", key.to_bytes().len(), enable, rc);
    rc
}

fn sc_pathhide_add(key: &CStr, path: &CStr) -> c_long {
    if key.to_bytes().is_empty() || path.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    let rc = unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_PATHHIDE_ADD),
            path.as_ptr(),
        ) as c_long
    };
    if rc < 0 {
        warn!("[diag:sc_pathhide_add] path='{}' rc={}", path.to_string_lossy(), rc);
    }
    rc
}

fn sc_pathhide_clear(key: &CStr) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    let rc = unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_PATHHIDE_CLEAR),
        ) as c_long
    };
    info!("[diag:sc_pathhide_clear] key_len={} rc={}", key.to_bytes().len(), rc);
    rc
}

fn sc_pathhide_uid_mode(key: &CStr, enable: bool) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_PATHHIDE_UID_MODE),
            if enable { 1i64 } else { 0i64 },
        ) as c_long
    }
}

fn sc_pathhide_filter_system(key: &CStr, enable: bool) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_PATHHIDE_FILTER_SYSTEM),
            if enable { 1i64 } else { 0i64 },
        ) as c_long
    }
}

fn sc_pathhide_uid_add(key: &CStr, uid: i32) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_PATHHIDE_UID_ADD),
            uid,
        ) as c_long
    }
}

fn sc_pathhide_uid_clear(key: &CStr) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_PATHHIDE_UID_CLEAR),
        ) as c_long
    }
}

fn sc_netisolate_enable(key: &CStr, enable: bool) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    let rc = unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_NETISOLATE_ENABLE),
            if enable { 1i64 } else { 0i64 },
        ) as c_long
    };
    info!("[diag:sc_netisolate_enable] key_len={} enable={} rc={}", key.to_bytes().len(), enable, rc);
    rc
}

fn sc_netisolate_uid_add(key: &CStr, uid: i32) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_NETISOLATE_UID_ADD),
            uid,
        ) as c_long
    }
}

fn sc_netisolate_uid_clear(key: &CStr) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_NETISOLATE_UID_CLEAR),
        ) as c_long
    }
}

pub fn apply_netisolate(superkey: &Option<String>) {
    if !std::path::Path::new(crate::defs::NETISOLATE_ENABLE_FILE).exists() {
        info!("[netisolate] disabled, skipping");
        return;
    }

    let key = convert_superkey(superkey);
    let key = match key {
        Some(k) => k,
        None => {
            warn!("[netisolate] no superkey available");
            return;
        }
    };

    // Step 1: Clear and populate UID blocklist (netisolate not yet enabled)
    match std::fs::read_to_string(crate::defs::NETISOLATE_UIDS_FILE) {
        Ok(uids) => {
            sc_netisolate_uid_clear(&key);
            let mut count = 0u32;
            for uid_str in uids.lines() {
                let uid_str = uid_str.trim();
                if uid_str.is_empty() {
                    continue;
                }
                match uid_str.parse::<i32>() {
                    Ok(uid) => {
                        let rc = sc_netisolate_uid_add(&key, uid);
                        if rc < 0 {
                            warn!("[netisolate] add uid {} failed: {}", uid, rc);
                        } else {
                            count += 1;
                        }
                    }
                    Err(_) => {
                        warn!("[netisolate] invalid uid: '{}'", uid_str);
                    }
                }
            }
            info!("[netisolate] {} uids restored", count);
        }
        Err(_) => {
            info!("[netisolate] no uids file");
        }
    }

    // Step 2: Enable netisolate LAST
    let rc = sc_netisolate_enable(&key, true);
    if rc < 0 {
        warn!("[netisolate] enable failed: {}", rc);
        return;
    }

    info!("[netisolate] auto-apply completed");
}

pub fn apply_pathhide(superkey: &Option<String>) {
    info!("[diag:pathhide] superkey_present={}", superkey.is_some());

    if !std::path::Path::new(crate::defs::PATHHIDE_ENABLE_FILE).exists() {
        set_retry_flag(crate::defs::PATHHIDE_RETRY_FILE, false, "pathhide");
        info!("[pathhide] disabled, skipping");
        return;
    }

    let key = convert_superkey(superkey);
    let key = match key {
        Some(k) => {
            info!("[diag:pathhide] key_len={}", k.to_bytes().len());
            k
        }
        None => {
            set_retry_flag(crate::defs::PATHHIDE_RETRY_FILE, true, "pathhide");
            warn!("[pathhide] no superkey available");
            return;
        }
    };

    let mut had_error = false;

    // Step 1: Clear and populate blocklist (pathhide not yet enabled, hooks are no-ops)
    match std::fs::read_to_string(crate::defs::PATHHIDE_PATHS_FILE) {
        Ok(paths) => {
            sc_pathhide_clear(&key);
            let mut count = 0u32;
            for path in paths.lines() {
                let Some(path) = normalize_pathhide_path(path) else {
                    continue;
                };
                match CString::new(path.as_str()) {
                    Ok(path_cstr) => {
                        let rc = sc_pathhide_add(&key, &path_cstr);
                        if rc < 0 {
                            had_error = true;
                            warn!("[pathhide] add path '{}' failed: {}", path, rc);
                        } else {
                            count += 1;
                        }
                    }
                    Err(e) => {
                        warn!("[pathhide] invalid path '{}': {}", path, e);
                    }
                }
            }
            info!("[pathhide] {} paths restored", count);
        }
        Err(_) => {
            info!("[pathhide] no paths file, clearing blocklist");
            sc_pathhide_clear(&key);
        }
    }

    // Step 2: Configure UID whitelist BEFORE enabling (so filters are ready)
    if std::path::Path::new(crate::defs::PATHHIDE_UID_MODE_FILE).exists() {
        match std::fs::read_to_string(crate::defs::PATHHIDE_UIDS_FILE) {
            Ok(uids) => {
                sc_pathhide_uid_clear(&key);
                let mut count = 0u32;
                for uid_str in uids.lines() {
                    let uid_str = uid_str.trim();
                    if uid_str.is_empty() {
                        continue;
                    }
                    match uid_str.parse::<i32>() {
                        Ok(uid) => {
                            let rc = sc_pathhide_uid_add(&key, uid);
                            if rc < 0 {
                                had_error = true;
                                warn!("[pathhide] add uid {} failed: {}", uid, rc);
                            } else {
                                count += 1;
                            }
                        }
                        Err(_) => {
                            warn!("[pathhide] invalid uid: '{}'", uid_str);
                        }
                    }
                }
                info!("[pathhide] {} uids restored", count);
            }
            Err(_) => {
                info!("[pathhide] no uids file");
            }
        }

        let rc = sc_pathhide_uid_mode(&key, true);
        if rc < 0 {
            had_error = true;
            warn!("[pathhide] uid mode enable failed: {}", rc);
        }
    }

    // Step 2.5: Configure filter_system (allow hiding from system/root UIDs)
    if std::path::Path::new(crate::defs::PATHHIDE_FILTER_SYSTEM_FILE).exists() {
        let rc = sc_pathhide_filter_system(&key, true);
        if rc < 0 {
            had_error = true;
            warn!("[pathhide] filter_system enable failed: {}", rc);
        }
    }

    // Step 3: Enable pathhide LAST (all config is now in place)
    let rc = sc_pathhide_enable(&key, true);
    if rc < 0 {
        set_retry_flag(crate::defs::PATHHIDE_RETRY_FILE, true, "pathhide");
        warn!("[pathhide] enable failed: {}", rc);
        return;
    }

    set_retry_flag(crate::defs::PATHHIDE_RETRY_FILE, had_error, "pathhide");
    if had_error {
        warn!("[pathhide] auto-apply completed with recoverable errors, retry requested");
    } else {
        info!("[pathhide] auto-apply completed");
    }
}

fn sc_uts_set(key: &CStr, release: Option<&CStr>, version: Option<&CStr>) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    let release_ptr = match release {
        Some(r) => r.as_ptr(),
        None => std::ptr::null(),
    };
    let version_ptr = match version {
        Some(v) => v.as_ptr(),
        None => std::ptr::null(),
    };
    let rc = unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_UTS_SET),
            release_ptr,
            version_ptr,
        ) as c_long
    };
    let rel_str = release.map(|r| r.to_string_lossy().into_owned()).unwrap_or_default();
    let ver_str = version.map(|v| v.to_string_lossy().into_owned()).unwrap_or_default();
    info!("[diag:sc_uts_set] key_len={} release='{}' version='{}' rc={}", key.to_bytes().len(), rel_str, ver_str, rc);
    rc
}

fn sc_uts_reset(key: &CStr) -> c_long {
    if key.to_bytes().is_empty() {
        return (-EINVAL).into();
    }
    let rc = unsafe {
        syscall(
            __NR_SUPERCALL,
            key.as_ptr(),
            ver_and_cmd(SUPERCALL_UTS_RESET),
        ) as c_long
    };
    info!("[diag:sc_uts_reset] key_len={} rc={}", key.to_bytes().len(), rc);
    rc
}

fn normalize_pathhide_path(path: &str) -> Option<String> {
    let trimmed = path.trim();
    if trimmed.is_empty() || !trimmed.starts_with('/') {
        return None;
    }

    let mut normalized = String::with_capacity(trimmed.len());
    let mut prev_was_slash = false;
    for ch in trimmed.chars() {
        if ch == '/' {
            if !prev_was_slash {
                normalized.push(ch);
            }
            prev_was_slash = true;
        } else {
            normalized.push(ch);
            prev_was_slash = false;
        }
    }

    while normalized.len() > 1 && normalized.ends_with('/') {
        normalized.pop();
    }

    if normalized.is_empty() {
        None
    } else {
        Some(normalized)
    }
}

pub fn apply_uts_spoof(superkey: &Option<String>) {
    use std::path::Path;

    const MAX_BOOT_RETRIES: u32 = 3;

    info!("[diag:uts_spoof] superkey_present={}", superkey.is_some());

    if !Path::new(crate::defs::UTS_SPOOF_ENABLE_FILE).exists() {
        set_retry_flag(crate::defs::UTS_SPOOF_RETRY_FILE, false, "uts_spoof");
        info!("[uts_spoof] disabled, skipping");
        return;
    }

    let config_content = match std::fs::read_to_string(crate::defs::UTS_SPOOF_CONFIG_FILE) {
        Ok(c) => c,
        Err(e) => {
            warn!("[uts_spoof] failed to read config: {}", e);
            return;
        }
    };

    let config: serde_json::Value = match serde_json::from_str(&config_content) {
        Ok(v) => v,
        Err(e) => {
            warn!("[uts_spoof] failed to parse config: {}", e);
            return;
        }
    };

    let release = config.get("release").and_then(|v| v.as_str()).unwrap_or("");
    let version = config.get("version").and_then(|v| v.as_str()).unwrap_or("");

    let key = convert_superkey(superkey);
    let key = match key {
        Some(k) => {
            info!("[diag:uts_spoof] key_len={}", k.to_bytes().len());
            k
        }
        None => {
            set_retry_flag(crate::defs::UTS_SPOOF_RETRY_FILE, true, "uts_spoof");
            warn!("[uts_spoof] no superkey available");
            return;
        }
    };

    let reset_rc = sc_uts_reset(&key);
    if reset_rc < 0 {
        set_retry_flag(crate::defs::UTS_SPOOF_RETRY_FILE, true, "uts_spoof");
        warn!("[uts_spoof] reset failed: {}", reset_rc);
    }

    let retries = match std::fs::read_to_string(crate::defs::UTS_SPOOF_BOOT_PENDING) {
        Ok(s) => s.trim().parse::<u32>().unwrap_or(0),
        Err(_) => 0,
    };

    if retries >= MAX_BOOT_RETRIES {
        warn!(
            "[uts_spoof] boot pending retries ({}) >= max ({}), skipping spoof to prevent bootloop",
            retries, MAX_BOOT_RETRIES
        );
        let _ = std::fs::remove_file(crate::defs::UTS_SPOOF_BOOT_PENDING);
        set_retry_flag(crate::defs::UTS_SPOOF_RETRY_FILE, false, "uts_spoof");
        return;
    }

    if let Err(e) = std::fs::write(
        crate::defs::UTS_SPOOF_BOOT_PENDING,
        (retries + 1).to_string(),
    ) {
        warn!("[uts_spoof] failed to write boot pending flag: {}", e);
    }

    // Only set if we have values to spoof
    let release_cstr = if !release.is_empty() {
        match CString::new(release) {
            Ok(c) => Some(c),
            Err(e) => {
                warn!("[uts_spoof] invalid release string: {}", e);
                None
            }
        }
    } else {
        None
    };
    let version_cstr = if !version.is_empty() {
        match CString::new(version) {
            Ok(c) => Some(c),
            Err(e) => {
                warn!("[uts_spoof] invalid version string: {}", e);
                None
            }
        }
    } else {
        None
    };

    if release_cstr.is_some() || version_cstr.is_some() {
        let rc = sc_uts_set(&key, release_cstr.as_deref(), version_cstr.as_deref());
        if rc == 0 {
            set_retry_flag(crate::defs::UTS_SPOOF_RETRY_FILE, false, "uts_spoof");
            info!(
                "[uts_spoof] applied: release='{}' version='{}'",
                release, version
            );
        } else {
            set_retry_flag(crate::defs::UTS_SPOOF_RETRY_FILE, true, "uts_spoof");
            warn!("[uts_spoof] set failed: {}", rc);
        }
    } else {
        set_retry_flag(crate::defs::UTS_SPOOF_RETRY_FILE, false, "uts_spoof");
        info!("[uts_spoof] config has empty values, skipping set");
    }
}
